/**
 * Fix Prompt Generator
 *
 * Generates deterministic, copy-paste fix prompts for every finding.
 * No AI. Templates are pre-written for each rule category.
 *
 * Supports: generic, cursor, lovable, bolt, replit
 */

export type FixTool = 'generic' | 'cursor' | 'lovable' | 'bolt' | 'replit';

export interface FixPrompt {
  findingId: string;
  tool: FixTool;
  title: string;
  prompt: string;
}

// ─── Tool-specific preambles ──────────────────────────────────────────────────

const TOOL_PREAMBLES: Record<FixTool, string> = {
  generic: '',
  cursor:
    'Open your project in Cursor and paste this into the chat. Make sure the relevant file is open.\n\n',
  lovable:
    'In Lovable, open the chat panel and paste this prompt:\n\n',
  bolt:
    'In Bolt.new, open the AI assistant and paste this prompt:\n\n',
  replit:
    'In Replit, open the AI assistant or chat and paste this prompt:\n\n',
};

// ─── Core finding types ───────────────────────────────────────────────────────

interface BaseFinding {
  id: string;
  ruleId: string;
  pageUrl: string;
  path: string;
  fixPrompt: string; // Already generated by the rule engine
  title: string;
}

// ─── Generic wrapper ──────────────────────────────────────────────────────────

/**
 * Generate fix prompts for all tools from a list of findings.
 * The rule engine provides the base fixPrompt; this function adds tool framing.
 */
export function generateFixPrompts(
  findings: BaseFinding[],
  tools: FixTool[] = ['generic', 'cursor', 'lovable', 'bolt', 'replit']
): FixPrompt[] {
  const prompts: FixPrompt[] = [];

  for (const finding of findings) {
    for (const tool of tools) {
      prompts.push({
        findingId: finding.id,
        tool,
        title: finding.title,
        prompt: TOOL_PREAMBLES[tool] + finding.fixPrompt,
      });
    }
  }

  return prompts;
}

/**
 * Get the single best fix prompt for a finding (generic version).
 */
export function getFixPrompt(finding: BaseFinding): string {
  return finding.fixPrompt;
}

/**
 * Get the fix prompt for a specific tool.
 */
export function getFixPromptForTool(finding: BaseFinding, tool: FixTool): string {
  return TOOL_PREAMBLES[tool] + finding.fixPrompt;
}

// ─── Category-level summary prompts ──────────────────────────────────────────

/**
 * Generates a single combined fix prompt for all findings in a category.
 * Useful for "fix all share preview issues in one go" type prompts.
 */
export function generateCategoryFixPrompt(
  category: string,
  findings: BaseFinding[],
  tool: FixTool = 'generic'
): string {
  if (findings.length === 0) return '';

  const issueList = findings
    .map((f, i) => `${i + 1}. [${f.path}] ${f.title}: ${f.fixPrompt}`)
    .join('\n\n');

  const categoryLabel = CATEGORY_LABELS[category] ?? category;

  const prompt = `Fix the following ${categoryLabel} issues:\n\n${issueList}\n\nAfter fixing each item, do not change unrelated UI or styling. Test each fix individually.`;

  return TOOL_PREAMBLES[tool] + prompt;
}

const CATEGORY_LABELS: Record<string, string> = {
  share_preview: 'share preview',
  metadata: 'metadata',
  links_routes: 'links and routes',
  public_exposure: 'public exposure',
  forms: 'form',
  ai_leftovers: 'AI leftover / placeholder content',
  key_patterns: 'potential exposed key',
  indexing: 'indexing',
  runtime: 'runtime',
};

// ─── Pre-built templates for common rules ─────────────────────────────────────
// These supplement rule-level prompts and can be used directly in the UI.

export const QUICK_FIX_TEMPLATES: Record<string, (ctx: {path: string; evidence?: any}) => string> = {
  missing_og_image: ({ path }) =>
    `Add an Open Graph image to ${path}. Create a 1200×630 pixel image and add these meta tags in the <head>:\n<meta property="og:image" content="https://yourdomain.com/og-image.png" />\n<meta name="twitter:image" content="https://yourdomain.com/og-image.png" />\nDo not change the visible layout. The image should represent the page visually.`,

  missing_og_title: ({ path }) =>
    `Add Open Graph title meta tag to ${path}:\n<meta property="og:title" content="Your Page Title" />\nMatch the value to the <title> tag. Do not change the visible heading.`,

  missing_og_description: ({ path }) =>
    `Add Open Graph description meta tag to ${path}:\n<meta property="og:description" content="A clear 150-character description of this page." />\nDo not change the visible page content.`,

  missing_twitter_card: ({ path }) =>
    `Add a Twitter card meta tag to ${path}:\n<meta name="twitter:card" content="summary_large_image" />\nAlso ensure twitter:title, twitter:description, and twitter:image are set. Do not change visible content.`,

  missing_favicon: ({ path }) =>
    `Add a favicon to ${path}. Create a 32×32 PNG or SVG and add this to the <head>:\n<link rel="icon" href="/favicon.ico" />\nAlso add a 180×180 Apple touch icon:\n<link rel="apple-touch-icon" href="/apple-touch-icon.png" />`,

  missing_title: ({ path }) =>
    `Add a <title> tag to the <head> of ${path}. Example:\n<title>Your Page Title — Brand Name</title>\nKeep it under 60 characters and include your primary keyword.`,

  missing_meta_description: ({ path }) =>
    `Add a meta description to ${path}:\n<meta name="description" content="A compelling 150-160 character description." />\nThis appears as the snippet text in search results.`,

  broken_internal_link: ({ path, evidence }) =>
    `Fix the broken internal link on ${path}. The link to "${evidence?.targetUrl}" returned a ${evidence?.statusCode} error. Either update the href to the correct URL, create the missing page, or remove the link. Do not change unrelated navigation.`,

  placeholder_link_hash: ({ path, evidence }) =>
    `Find the link with href="#" on ${path} (anchor text: "${evidence?.anchorText || 'unknown'}"). Replace it with the correct destination route or remove the CTA if the destination is not ready.`,

  missing_robots_txt: ({ path }) =>
    `Create a robots.txt file at the root of your project (public/robots.txt or in the static folder). Minimum content:\nUser-agent: *\nAllow: /\nSitemap: https://yourdomain.com/sitemap.xml`,

  missing_sitemap: ({ path }) =>
    `Create a sitemap.xml at /sitemap.xml listing your public pages. For Next.js, use next-sitemap or add a dynamic route at app/sitemap.ts. Include all public marketing pages.`,

  console_error: ({ path, evidence }) =>
    `Fix the JavaScript console error on ${path}: "${evidence?.message || 'unknown error'}". Open your browser DevTools, reproduce the error, and trace it to its source. Do not change unrelated code.`,
};
