// Issue Knowledge Base - Rich metadata for all issue types

export interface IssueDefinition {
  code: string;
  title: string;
  defaultSeverity: 'critical' | 'warning' | 'info';
  category: string;
  whatChecked: string;
  whyItMatters: string;
  businessImpact: string;
  developerFix: string;
  sampleFix: string;
  launchBlocker: boolean;
  estimatedFixTime: string;
  ownerRole: string;
  priority: number;
  canLaunchWithoutFixing: boolean;
}

export const ISSUE_KNOWLEDGE_BASE: Record<string, IssueDefinition> = {
  homepage_unreachable: {
    code: 'homepage_unreachable',
    title: 'Homepage Unreachable',
    defaultSeverity: 'critical',
    category: 'accessibility',
    whatChecked: 'HTTP request to the homepage URL',
    whyItMatters: 'If your homepage is down, visitors cannot access your site at all',
    businessImpact: 'Complete site inaccessibility. No traffic, no conversions, damaged brand reputation.',
    developerFix: 'Check server status, DNS configuration, and deployment. Ensure the web server is running.',
    sampleFix: 'Verify hosting is active, domain is pointed correctly, and no firewall blocking.',
    launchBlocker: true,
    estimatedFixTime: '30-120 minutes',
    ownerRole: 'DevOps/Backend',
    priority: 100,
    canLaunchWithoutFixing: false,
  },

  page_4xx: {
    code: 'page_4xx',
    title: 'Page Returns 4xx Error',
    defaultSeverity: 'critical',
    category: 'accessibility',
    whatChecked: 'HTTP status code of the page',
    whyItMatters: '4xx errors mean the page is not found or forbidden',
    businessImpact: 'Broken user experience. Visitors hit dead ends. Lost conversions.',
    developerFix: 'Check route configuration, file paths, and server redirects. Create the missing page or remove broken links.',
    sampleFix: 'If page should exist: create it. If not: remove links pointing to it or set up 301 redirect.',
    launchBlocker: true,
    estimatedFixTime: '15-60 minutes',
    ownerRole: 'Backend/Frontend',
    priority: 95,
    canLaunchWithoutFixing: false,
  },

  page_5xx: {
    code: 'page_5xx',
    title: 'Page Returns 5xx Server Error',
    defaultSeverity: 'critical',
    category: 'accessibility',
    whatChecked: 'HTTP status code of the page',
    whyItMatters: '5xx errors indicate server-side problems preventing page load',
    businessImpact: 'Site crashes. User frustration. Lost revenue. Damaged credibility.',
    developerFix: 'Check server logs, database connections, API dependencies, and error handling.',
    sampleFix: 'Review application logs, fix bugs, ensure all services are running, add error boundaries.',
    launchBlocker: true,
    estimatedFixTime: '30-180 minutes',
    ownerRole: 'Backend/DevOps',
    priority: 98,
    canLaunchWithoutFixing: false,
  },

  missing_title: {
    code: 'missing_title',
    title: 'Missing Page Title',
    defaultSeverity: 'critical',
    category: 'seo',
    whatChecked: 'Presence of <title> tag in <head>',
    whyItMatters: 'Page titles appear in search results and browser tabs. Without one, your page looks unprofessional.',
    businessImpact: 'Poor SEO ranking. Reduced click-through rates from search. Generic "Untitled" browser tabs.',
    developerFix: 'Add a <title> tag inside the <head> section of your HTML.',
    sampleFix: '<title>Your Page Title Here - Brand Name</title>',
    launchBlocker: false,
    estimatedFixTime: '5-10 minutes',
    ownerRole: 'SEO/Frontend',
    priority: 85,
    canLaunchWithoutFixing: true,
  },

  title_too_short: {
    code: 'title_too_short',
    title: 'Page Title Too Short',
    defaultSeverity: 'warning',
    category: 'seo',
    whatChecked: 'Length of <title> tag text',
    whyItMatters: 'Titles under 30 characters may not provide enough context for search engines and users.',
    businessImpact: 'Suboptimal SEO. Less informative search results. Reduced click-through rates.',
    developerFix: 'Expand the title to include primary keywords and brand name. Aim for 50-60 characters.',
    sampleFix: '<title>Product Name - Key Benefit | Brand Name</title>',
    launchBlocker: false,
    estimatedFixTime: '10 minutes',
    ownerRole: 'SEO/Content',
    priority: 50,
    canLaunchWithoutFixing: true,
  },

  title_too_long: {
    code: 'title_too_long',
    title: 'Page Title Too Long',
    defaultSeverity: 'warning',
    category: 'seo',
    whatChecked: 'Length of <title> tag text',
    whyItMatters: 'Titles over 60 characters get truncated in search results with "..."',
    businessImpact: 'Truncated search results. Key information cut off. Lower click-through rates.',
    developerFix: 'Shorten the title to under 60 characters. Put the most important words first.',
    sampleFix: '<title>Key Benefit - Brand (under 60 chars)</title>',
    launchBlocker: false,
    estimatedFixTime: '10 minutes',
    ownerRole: 'SEO/Content',
    priority: 45,
    canLaunchWithoutFixing: true,
  },

  missing_meta_description: {
    code: 'missing_meta_description',
    title: 'Missing Meta Description',
    defaultSeverity: 'warning',
    category: 'seo',
    whatChecked: 'Presence of <meta name="description"> tag',
    whyItMatters: 'Meta descriptions appear as the snippet text in search results. Without one, search engines show random page text.',
    businessImpact: 'Poor search result presentation. Lower click-through rates. Missed opportunity to sell your page.',
    developerFix: 'Add a <meta name="description" content="..."> tag in the <head>.',
    sampleFix: '<meta name="description" content="Compelling 150-160 character description of your page that encourages clicks from search results.">',
    launchBlocker: false,
    estimatedFixTime: '10-15 minutes',
    ownerRole: 'SEO/Content',
    priority: 75,
    canLaunchWithoutFixing: true,
  },

  meta_description_too_short: {
    code: 'meta_description_too_short',
    title: 'Meta Description Too Short',
    defaultSeverity: 'warning',
    category: 'seo',
    whatChecked: 'Length of meta description content',
    whyItMatters: 'Descriptions under 120 characters don\'t fully utilize the search result snippet space.',
    businessImpact: 'Wasted real estate in search results. Less persuasive snippets.',
    developerFix: 'Expand the description to 150-160 characters with compelling benefits and keywords.',
    sampleFix: 'Add more details about the page value, target keywords, and call-to-action.',
    launchBlocker: false,
    estimatedFixTime: '10 minutes',
    ownerRole: 'SEO/Content',
    priority: 40,
    canLaunchWithoutFixing: true,
  },

  meta_description_too_long: {
    code: 'meta_description_too_long',
    title: 'Meta Description Too Long',
    defaultSeverity: 'warning',
    category: 'seo',
    whatChecked: 'Length of meta description content',
    whyItMatters: 'Descriptions over 160 characters get truncated in search results.',
    businessImpact: 'Incomplete messaging in search snippets. Key information cut off.',
    developerFix: 'Trim the description to 150-160 characters. Put key information first.',
    sampleFix: 'Reduce wordiness. Focus on primary value proposition and keywords.',
    launchBlocker: false,
    estimatedFixTime: '10 minutes',
    ownerRole: 'SEO/Content',
    priority: 40,
    canLaunchWithoutFixing: true,
  },

  missing_h1: {
    code: 'missing_h1',
    title: 'Missing H1 Heading',
    defaultSeverity: 'warning',
    category: 'seo',
    whatChecked: 'Presence of <h1> tag on the page',
    whyItMatters: 'H1 tags signal the main topic of the page to search engines and users.',
    businessImpact: 'Weaker SEO signals. Less clear page hierarchy. Reduced accessibility.',
    developerFix: 'Add an <h1> tag with the primary heading for the page content.',
    sampleFix: '<h1>Main Page Heading</h1>',
    launchBlocker: false,
    estimatedFixTime: '5-10 minutes',
    ownerRole: 'Frontend/SEO',
    priority: 70,
    canLaunchWithoutFixing: true,
  },

  multiple_h1: {
    code: 'multiple_h1',
    title: 'Multiple H1 Headings',
    defaultSeverity: 'warning',
    category: 'seo',
    whatChecked: 'Count of <h1> tags on the page',
    whyItMatters: 'Multiple H1s confuse search engines about the page\'s main topic.',
    businessImpact: 'Diluted SEO signals. Unclear content hierarchy.',
    developerFix: 'Use only one H1 per page for the main heading. Convert others to H2 or H3.',
    sampleFix: 'Change <h1> tags to <h2> or <h3> except for the main page heading.',
    launchBlocker: false,
    estimatedFixTime: '10-15 minutes',
    ownerRole: 'Frontend/SEO',
    priority: 55,
    canLaunchWithoutFixing: true,
  },

  missing_canonical: {
    code: 'missing_canonical',
    title: 'Missing Canonical Tag',
    defaultSeverity: 'warning',
    category: 'seo',
    whatChecked: 'Presence of <link rel="canonical"> tag',
    whyItMatters: 'Canonical tags prevent duplicate content issues when the same page is accessible via multiple URLs.',
    businessImpact: 'Diluted SEO value across duplicate URLs. Potential ranking penalties.',
    developerFix: 'Add a canonical link tag pointing to the preferred version of the page.',
    sampleFix: '<link rel="canonical" href="https://example.com/page" />',
    launchBlocker: false,
    estimatedFixTime: '10-15 minutes',
    ownerRole: 'SEO/Frontend',
    priority: 60,
    canLaunchWithoutFixing: true,
  },

  missing_og_title: {
    code: 'missing_og_title',
    title: 'Missing Open Graph Title',
    defaultSeverity: 'warning',
    category: 'social',
    whatChecked: 'Presence of <meta property="og:title"> tag',
    whyItMatters: 'When your page is shared on Facebook, LinkedIn, or Slack, og:title controls the displayed title.',
    businessImpact: 'Unprofessional social sharing. Generic link previews. Reduced click-through from social media.',
    developerFix: 'Add og:title meta tag in the <head>.',
    sampleFix: '<meta property="og:title" content="Your Page Title for Social Sharing" />',
    launchBlocker: false,
    estimatedFixTime: '5-10 minutes',
    ownerRole: 'Frontend/Marketing',
    priority: 50,
    canLaunchWithoutFixing: true,
  },

  missing_og_description: {
    code: 'missing_og_description',
    title: 'Missing Open Graph Description',
    defaultSeverity: 'warning',
    category: 'social',
    whatChecked: 'Presence of <meta property="og:description"> tag',
    whyItMatters: 'og:description controls the text shown when your page is shared on social platforms.',
    businessImpact: 'Poor social media previews. Missed opportunity to entice clicks from shares.',
    developerFix: 'Add og:description meta tag in the <head>.',
    sampleFix: '<meta property="og:description" content="Compelling description for social sharing" />',
    launchBlocker: false,
    estimatedFixTime: '5-10 minutes',
    ownerRole: 'Frontend/Marketing',
    priority: 48,
    canLaunchWithoutFixing: true,
  },

  missing_og_image: {
    code: 'missing_og_image',
    title: 'Missing Open Graph Image',
    defaultSeverity: 'warning',
    category: 'social',
    whatChecked: 'Presence of <meta property="og:image"> tag',
    whyItMatters: 'og:image is the preview image shown when your page is shared. Without it, no image appears or a random one is picked.',
    businessImpact: 'Unattractive social shares. Significantly lower engagement and click-through rates.',
    developerFix: 'Add og:image meta tag pointing to a high-quality image (min 1200x630px recommended).',
    sampleFix: '<meta property="og:image" content="https://example.com/image.jpg" />',
    launchBlocker: false,
    estimatedFixTime: '15-30 minutes',
    ownerRole: 'Frontend/Design',
    priority: 65,
    canLaunchWithoutFixing: true,
  },

  missing_twitter_card: {
    code: 'missing_twitter_card',
    title: 'Missing Twitter Card',
    defaultSeverity: 'warning',
    category: 'social',
    whatChecked: 'Presence of <meta name="twitter:card"> tag',
    whyItMatters: 'Twitter card tags control how your links appear when shared on Twitter/X.',
    businessImpact: 'Plain text links on Twitter. Lower engagement from tweets.',
    developerFix: 'Add twitter:card meta tag in the <head>.',
    sampleFix: '<meta name="twitter:card" content="summary_large_image" />',
    launchBlocker: false,
    estimatedFixTime: '5-10 minutes',
    ownerRole: 'Frontend/Marketing',
    priority: 45,
    canLaunchWithoutFixing: true,
  },

  missing_favicon: {
    code: 'missing_favicon',
    title: 'Missing Favicon',
    defaultSeverity: 'warning',
    category: 'branding',
    whatChecked: 'Presence of <link rel="icon"> tag',
    whyItMatters: 'Favicon appears in browser tabs and bookmarks. Missing favicon looks unprofessional.',
    businessImpact: 'Generic browser icon. Weak brand presence. Looks unfinished.',
    developerFix: 'Add a favicon link tag and include a favicon.ico file in your site root.',
    sampleFix: '<link rel="icon" href="/favicon.ico" />',
    launchBlocker: false,
    estimatedFixTime: '10-20 minutes',
    ownerRole: 'Frontend/Design',
    priority: 40,
    canLaunchWithoutFixing: true,
  },

  missing_viewport: {
    code: 'missing_viewport',
    title: 'Missing Viewport Meta Tag',
    defaultSeverity: 'critical',
    category: 'mobile',
    whatChecked: 'Presence of <meta name="viewport"> tag',
    whyItMatters: 'Viewport tag is required for mobile responsiveness. Without it, your site will look zoomed out on phones.',
    businessImpact: 'Broken mobile experience. Users will pinch and zoom. High bounce rates on mobile.',
    developerFix: 'Add viewport meta tag in the <head>.',
    sampleFix: '<meta name="viewport" content="width=device-width, initial-scale=1.0" />',
    launchBlocker: true,
    estimatedFixTime: '2 minutes',
    ownerRole: 'Frontend',
    priority: 90,
    canLaunchWithoutFixing: false,
  },

  robots_noindex: {
    code: 'robots_noindex',
    title: 'Page Has noindex Directive',
    defaultSeverity: 'critical',
    category: 'seo',
    whatChecked: 'Presence of <meta name="robots" content="noindex">',
    whyItMatters: 'noindex tells search engines not to index this page. This is usually a mistake before launch.',
    businessImpact: 'Page will not appear in search results. Zero organic traffic.',
    developerFix: 'Remove the noindex directive or change to "index, follow".',
    sampleFix: 'Remove <meta name="robots" content="noindex"> or change to <meta name="robots" content="index, follow">',
    launchBlocker: true,
    estimatedFixTime: '5 minutes',
    ownerRole: 'SEO/Frontend',
    priority: 100,
    canLaunchWithoutFixing: false,
  },

  broken_internal_link: {
    code: 'broken_internal_link',
    title: 'Broken Internal Link',
    defaultSeverity: 'critical',
    category: 'links',
    whatChecked: 'HTTP status code of internal link target',
    whyItMatters: 'Broken internal links create dead ends for users and hurt SEO.',
    businessImpact: 'Frustrating user experience. Lost conversions. SEO penalties.',
    developerFix: 'Fix the link URL or create the missing page.',
    sampleFix: 'Update href to correct URL or remove the link if page no longer exists.',
    launchBlocker: true,
    estimatedFixTime: '5-15 minutes',
    ownerRole: 'Frontend/Content',
    priority: 85,
    canLaunchWithoutFixing: false,
  },

  broken_external_link: {
    code: 'broken_external_link',
    title: 'Broken External Link',
    defaultSeverity: 'warning',
    category: 'links',
    whatChecked: 'HTTP status code of external link target',
    whyItMatters: 'Broken external links hurt credibility and user experience.',
    businessImpact: 'Poor user experience. Looks unmaintained.',
    developerFix: 'Update the link to a working URL or remove it.',
    sampleFix: 'Find replacement URL or remove the broken link.',
    launchBlocker: false,
    estimatedFixTime: '5-10 minutes',
    ownerRole: 'Content',
    priority: 60,
    canLaunchWithoutFixing: true,
  },

  redirect_link: {
    code: 'redirect_link',
    title: 'Link Points to Redirect',
    defaultSeverity: 'info',
    category: 'links',
    whatChecked: 'HTTP status code and redirect chain of link target',
    whyItMatters: 'Redirects add latency and extra server requests.',
    businessImpact: 'Slightly slower page loads. Minor SEO impact.',
    developerFix: 'Update link to point directly to the final destination URL.',
    sampleFix: 'Change href from redirect URL to final URL.',
    launchBlocker: false,
    estimatedFixTime: '5 minutes',
    ownerRole: 'Frontend',
    priority: 30,
    canLaunchWithoutFixing: true,
  },

  image_missing_alt: {
    code: 'image_missing_alt',
    title: 'Images Missing Alt Text',
    defaultSeverity: 'warning',
    category: 'accessibility',
    whatChecked: 'Presence of alt attribute on <img> tags',
    whyItMatters: 'Alt text is critical for screen readers and SEO. Without it, visually impaired users can\'t understand images.',
    businessImpact: 'Accessibility violations. Potential lawsuits. Poor SEO for images.',
    developerFix: 'Add descriptive alt text to all images.',
    sampleFix: '<img src="logo.png" alt="Company Name Logo" />',
    launchBlocker: false,
    estimatedFixTime: '15-30 minutes',
    ownerRole: 'Frontend/Content',
    priority: 70,
    canLaunchWithoutFixing: true,
  },

  form_missing_action: {
    code: 'form_missing_action',
    title: 'Form Missing Action Attribute',
    defaultSeverity: 'warning',
    category: 'forms',
    whatChecked: 'Presence of action attribute on <form> tags',
    whyItMatters: 'Forms without action may not submit correctly.',
    businessImpact: 'Broken form submissions. Lost leads.',
    developerFix: 'Add action attribute or handle submission with JavaScript.',
    sampleFix: '<form action="/submit" method="POST">',
    launchBlocker: false,
    estimatedFixTime: '10-20 minutes',
    ownerRole: 'Frontend/Backend',
    priority: 75,
    canLaunchWithoutFixing: true,
  },

  form_missing_method: {
    code: 'form_missing_method',
    title: 'Form Missing Method Attribute',
    defaultSeverity: 'info',
    category: 'forms',
    whatChecked: 'Presence of method attribute on <form> tags',
    whyItMatters: 'Forms default to GET if method is missing, which may not be intended.',
    businessImpact: 'Data may be sent insecurely via URL parameters.',
    developerFix: 'Add method="POST" to forms that submit data.',
    sampleFix: '<form method="POST">',
    launchBlocker: false,
    estimatedFixTime: '5 minutes',
    ownerRole: 'Frontend',
    priority: 50,
    canLaunchWithoutFixing: true,
  },

  form_inputs_missing_labels: {
    code: 'form_inputs_missing_labels',
    title: 'Form Inputs Missing Labels',
    defaultSeverity: 'warning',
    category: 'accessibility',
    whatChecked: 'Presence of <label> tags for form inputs',
    whyItMatters: 'Labels are essential for accessibility. Screen readers can\'t identify unlabeled inputs.',
    businessImpact: 'Accessibility violations. Poor user experience. Potential legal issues.',
    developerFix: 'Add <label> tags with for attributes matching input IDs.',
    sampleFix: '<label for="email">Email:</label><input id="email" type="email" />',
    launchBlocker: false,
    estimatedFixTime: '15-30 minutes',
    ownerRole: 'Frontend',
    priority: 65,
    canLaunchWithoutFixing: true,
  },

  console_error: {
    code: 'console_error',
    title: 'JavaScript Console Error',
    defaultSeverity: 'warning',
    category: 'technical',
    whatChecked: 'Browser console errors',
    whyItMatters: 'Console errors indicate broken JavaScript that may affect functionality.',
    businessImpact: 'Potential broken features. Poor user experience.',
    developerFix: 'Review and fix the JavaScript error.',
    sampleFix: 'Check browser console, identify the error source, and fix the code.',
    launchBlocker: false,
    estimatedFixTime: '15-60 minutes',
    ownerRole: 'Frontend',
    priority: 70,
    canLaunchWithoutFixing: true,
  },

  failed_network_request: {
    code: 'failed_network_request',
    title: 'Failed Network Request',
    defaultSeverity: 'warning',
    category: 'technical',
    whatChecked: 'Network requests made by the page',
    whyItMatters: 'Failed requests indicate broken API calls or missing resources.',
    businessImpact: 'Broken features. Missing data. Poor user experience.',
    developerFix: 'Check network tab, verify API endpoints, and fix failed requests.',
    sampleFix: 'Verify API is accessible, check CORS settings, fix request URLs.',
    launchBlocker: false,
    estimatedFixTime: '20-60 minutes',
    ownerRole: 'Backend/Frontend',
    priority: 75,
    canLaunchWithoutFixing: true,
  },

  missing_robots_txt: {
    code: 'missing_robots_txt',
    title: 'Missing robots.txt File',
    defaultSeverity: 'info',
    category: 'seo',
    whatChecked: 'Presence of /robots.txt file',
    whyItMatters: 'robots.txt tells search engines which pages to crawl. While not required, it\'s a best practice.',
    businessImpact: 'Search engines may crawl pages you don\'t want indexed.',
    developerFix: 'Create a robots.txt file in your site root.',
    sampleFix: 'Create /robots.txt with: User-agent: *\\nAllow: /',
    launchBlocker: false,
    estimatedFixTime: '10 minutes',
    ownerRole: 'SEO/Backend',
    priority: 35,
    canLaunchWithoutFixing: true,
  },

  missing_sitemap: {
    code: 'missing_sitemap',
    title: 'Missing XML Sitemap',
    defaultSeverity: 'info',
    category: 'seo',
    whatChecked: 'Presence of sitemap reference in robots.txt or common sitemap URLs',
    whyItMatters: 'Sitemaps help search engines discover all your pages.',
    businessImpact: 'Slower indexing of new pages. Potential missed pages in search results.',
    developerFix: 'Create an XML sitemap and submit it to search consoles.',
    sampleFix: 'Generate sitemap.xml and add to robots.txt: Sitemap: https://example.com/sitemap.xml',
    launchBlocker: false,
    estimatedFixTime: '20-30 minutes',
    ownerRole: 'SEO/Backend',
    priority: 40,
    canLaunchWithoutFixing: true,
  },

  http_not_https: {
    code: 'http_not_https',
    title: 'Site Not Using HTTPS',
    defaultSeverity: 'critical',
    category: 'security',
    whatChecked: 'URL protocol (HTTP vs HTTPS)',
    whyItMatters: 'HTTPS encrypts data and is required for security. Browsers show warnings for HTTP sites.',
    businessImpact: 'Security warnings. Lost trust. SEO penalties. Lower rankings.',
    developerFix: 'Install SSL certificate and redirect all HTTP traffic to HTTPS.',
    sampleFix: 'Get SSL cert from Let\'s Encrypt or hosting provider. Set up HTTPS redirect.',
    launchBlocker: true,
    estimatedFixTime: '30-60 minutes',
    ownerRole: 'DevOps/Backend',
    priority: 95,
    canLaunchWithoutFixing: false,
  },
};

// Helper function to get issue definition
export function getIssueDefinition(code: string): IssueDefinition | undefined {
  return ISSUE_KNOWLEDGE_BASE[code];
}

// Helper function to create an issue from a code
export function createIssueFromCode(
  code: string,
  affectedUrl: string,
  whatFound: string,
  evidenceJson: Record<string, any> = {},
  overrides: Partial<IssueDefinition> = {}
): any {
  const definition = getIssueDefinition(code);
  if (!definition) {
    throw new Error(`Unknown issue code: ${code}`);
  }

  return {
    issueCode: code,
    severity: overrides.defaultSeverity || definition.defaultSeverity,
    category: overrides.category || definition.category,
    affectedUrl,
    title: overrides.title || definition.title,
    description: whatFound,
    whatChecked: overrides.whatChecked || definition.whatChecked,
    whatFound,
    whyItMatters: overrides.whyItMatters || definition.whyItMatters,
    businessImpact: overrides.businessImpact || definition.businessImpact,
    developerFix: overrides.developerFix || definition.developerFix,
    sampleFix: overrides.sampleFix || definition.sampleFix,
    evidenceJson,
    priority: overrides.priority || definition.priority,
    estimatedFixTime: overrides.estimatedFixTime || definition.estimatedFixTime,
    ownerRole: overrides.ownerRole || definition.ownerRole,
    launchBlocker: overrides.launchBlocker ?? definition.launchBlocker,
    canLaunchWithoutFixing: overrides.canLaunchWithoutFixing ?? definition.canLaunchWithoutFixing,
    groupedKey: `${code}_${definition.category}`,
    // Legacy compatibility
    fix: definition.developerFix,
    page: affectedUrl,
    evidence: JSON.stringify(evidenceJson),
  };
}
